### ISSUE TITLE
bzero is not return (void *)

### ISSUE THREAD

**Issue by shwatanap** [usatie/libft-tester-tokyo#1]
Hi! Thank you for making very cool tester.

Your bzero test expected return (void *).
But libc bzero is void function.

Please check `man bzero`.

**Comment by usatie** [comment]
Thanks!
Resolved in 21a772647a7097e7cc4eb5658edb3fa78c3ffccc.

**Comment by usatie** [comment]
Ooops, it was not fully fixed.
And fixed it again in d52a1c84fec49c981c7fb6c6f0d4533431991400.
